<?php

namespace Europa\Exception;

/**
 * Makes it easier to trigger exceptions with formatter messages.
 * 
 * @category Events
 * @package  Europa
 * @author   Trey Shugart <treshugart@gmail.com>
 * @license  Copyright (c) 2011 Trey Shugart http://europaphp.org/license
 */
class Exception extends \Exception
{
    /**
     * Static way of throwing a new exception and formatting the message using `sprintf`.
     * 
     * @throws Exception
     * 
     * @return void
     */
    public static function toss()
    {
        throw new static(call_user_func_array('sprintf', func_get_args()), static::code());
    }

    /**
     * Returns an autogenerated code of the exception.
     * 
     * @return string
     */
    public static function code()
    {
        return crc32(get_called_class());
    }
}